//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;
//using System.ComponentModel.DataAnnotations;

[assembly: EdmSchemaAttribute()]

namespace TodoWebApplication
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class TodoEntitiesContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new TodoEntitiesContainer object using the connection string found in the 'TodoEntitiesContainer' section of the application configuration file.
        /// </summary>
        public TodoEntitiesContainer() : base("name=TodoEntitiesContainer", "TodoEntitiesContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TodoEntitiesContainer object.
        /// </summary>
        public TodoEntitiesContainer(string connectionString) : base(connectionString, "TodoEntitiesContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TodoEntitiesContainer object.
        /// </summary>
        public TodoEntitiesContainer(EntityConnection connection) : base(connection, "TodoEntitiesContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Todo> TodoSet
        {
            get
            {
                if ((_TodoSet == null))
                {
                    _TodoSet = base.CreateObjectSet<Todo>("TodoSet");
                }
                return _TodoSet;
            }
        }
        private ObjectSet<Todo> _TodoSet;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TodoSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTodoSet(Todo todo)
        {
            base.AddObject("TodoSet", todo);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TodoEntities", Name="Todo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Todo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Todo object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="order">Initial value of the Order property.</param>
        /// <param name="done">Initial value of the Done property.</param>
        /// <param name="text">Initial value of the Text property.</param>
        public static Todo CreateTodo(global::System.Int32 id, global::System.Int32 order, global::System.Boolean done, global::System.String text)
        {
            Todo todo = new Todo();
            todo.Id = id;
            todo.Order = order;
            todo.Done = done;
            todo.Text = text;
            return todo;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Order
        {
            get
            {
                return _Order;
            }
            set
            {
                OnOrderChanging(value);
                ReportPropertyChanging("Order");
                _Order = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Order");
                OnOrderChanged();
            }
        }
        private global::System.Int32 _Order;
        partial void OnOrderChanging(global::System.Int32 value);
        partial void OnOrderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Done
        {
            get
            {
                return _Done;
            }
            set
            {
                OnDoneChanging(value);
                ReportPropertyChanging("Done");
                _Done = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Done");
                OnDoneChanged();
            }
        }
        private global::System.Boolean _Done;
        partial void OnDoneChanging(global::System.Boolean value);
        partial void OnDoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        //[MinLength(10)]
        public global::System.String Text
        {
            get
            {
                return _Text;
            }
            set
            {
                OnTextChanging(value);
                ReportPropertyChanging("Text");
                _Text = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Text");
                OnTextChanged();
            }
        }
        private global::System.String _Text;
        partial void OnTextChanging(global::System.String value);
        partial void OnTextChanged();

        #endregion
    
    }

    #endregion
    
}
